### ISSUE TITLE
Please realease version 1.0.3

### ISSUE THREAD

**Issue by madsdyd** [miko007/SerialTerminal#1]
Hi there.

When using vscode or Arduino, the version that gets downloaded is 1.0.2, which is not the same as the version here on github. Please bump the version number and release the existing code.

Thanks.

**Comment by miko007** [comment]
hello, nice to see someone else use this library. the version is currently not live for arduino ide, because it is not in a stables state. there are some issues with esp8266 and esp32 boards, which i still have to figure out/fix.

that said, i will merge and release your pull request in a reasonable amount of time, so everyone can use it.

**Comment by madsdyd** [comment]
Hi miko. 

I am using esp32, and the off by one fix fixes a crash on the esp32 for me. Basically I would assume the code as it is, would never work for esp32 (and probably not 8266 either). Perhaps it would work for others too.

I have a jtag debugger hooked up to my esp32 platform, so if you attach a sketch that fails for esp32, I can run it through the debugger.

**Comment by miko007** [comment]
that is nice to know! i can not do testing on esp atm, as the latest release of macOS messed up the drivers for the ftdi chip. i will look into it when this problem is resolved.

**Comment by madsdyd** [comment]
Well, works my end *with the changes*.

BR

**Comment by miko007** [comment]
we now released `v1.1.1` with your submitted changes applied. thank you again for pointing that stupid typo out.
